--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AetherPlace/KnockbackFFA
build-by-default: true
branches:
- main
projects:
  KnockbackFFA:
    path: ""
    image: "https://raw.githubusercontent.com/AetherPlace/KnockbackFFA/main/KnockbackFFA.gif"
...
