--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AetherPlace/KnockbackFFA
build-by-default: true
branches:
- main
projects:
  KnockbackFFA:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
    libs:
    - src: "CortexPE/Commando/Commando"
      version: ^3.0.0
    - src: "jojoe77777/FormAPI/libFormAPI"
      version: ^1.3.0
    - src: "JackMD/UpdateNotifier/UpdateNotifier"
      version: ^2.1.0
...