--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AetherPlace/KnockbackFFA
build-by-default: true
branches:
- main
projects:
  KnockbackFFA:
    path: ""
    icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/bf/Debug_Stick.gif/revision/latest?cb=20200428014035&format=original"
...
