--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AetherPlace/KnockbackFFA
build-by-default: true
branches:
- main
projects:
  KnockbackFFA:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
...
